"""robots.txt Generator — generate AI-friendly robots.txt from analysis."""
from __future__ import annotations

from datetime import UTC, datetime

# All known AI crawlers with recommended rules
_AI_CRAWLERS = [
    # Core search crawlers (should Allow for visibility)
    {"ua": "GPTBot", "purpose": "ChatGPT Search", "recommend": "Allow"},
    {"ua": "OAI-SearchBot", "purpose": "SearchGPT", "recommend": "Allow"},
    {"ua": "ClaudeBot", "purpose": "Claude Search", "recommend": "Allow"},
    {"ua": "PerplexityBot", "purpose": "Perplexity", "recommend": "Allow"},
    {"ua": "Google-Extended", "purpose": "Gemini/AI Overviews", "recommend": "Allow"},
    {"ua": "Applebot-Extended", "purpose": "Apple Intelligence", "recommend": "Allow"},
    # Extended crawlers
    {"ua": "Amazonbot", "purpose": "Alexa/Rufus", "recommend": "Allow"},
    {"ua": "YouBot", "purpose": "You.com", "recommend": "Allow"},
    {"ua": "PhindBot", "purpose": "Phind", "recommend": "Allow"},
    {"ua": "Meta-ExternalAgent", "purpose": "Meta AI", "recommend": "Allow"},
    # Training-only crawlers (user may want to Disallow)
    {"ua": "CCBot", "purpose": "Common Crawl (training)", "recommend": "Allow"},
    {"ua": "anthropic-ai", "purpose": "Anthropic (training)", "recommend": "Allow"},
    {"ua": "cohere-ai", "purpose": "Cohere (training)", "recommend": "Allow"},
    {"ua": "Bytespider", "purpose": "ByteDance (training)", "recommend": "Allow"},
]


def generate_robots_txt(
    geo_result: dict,
    url: str = "",
    *,
    allow_training: bool = True,
    sitemap_url: str = "",
) -> str:
    """Generate recommended robots.txt content.

    Args:
        geo_result: GEO analysis result dict
        url: The analyzed URL (used for Sitemap hint)
        allow_training: If False, Disallow training-only crawlers
        sitemap_url: Custom sitemap URL to include
    """
    lines: list[str] = []
    now = datetime.now(UTC).strftime("%Y-%m-%d")

    lines.append(f"# robots.txt — AI-optimized (generated by GEO Checker on {now})")
    lines.append("# Source: https://gc.ranran.tw")
    lines.append("")

    # General rules
    lines.append("# General crawlers")
    lines.append("User-agent: *")
    lines.append("Allow: /")
    lines.append("")

    # AI crawler rules
    lines.append("# === AI Search Crawlers (recommended: Allow for GEO visibility) ===")
    lines.append("")

    for crawler in _AI_CRAWLERS:
        ua = crawler["ua"]
        purpose = crawler["purpose"]
        is_training = "training" in purpose.lower()

        if is_training and not allow_training:
            rule = "Disallow: /"
            note = "blocked (training-only)"
        else:
            rule = "Allow: /"
            note = purpose

        lines.append(f"# {note}")
        lines.append(f"User-agent: {ua}")
        lines.append(rule)
        lines.append("")

    # Sitemap
    if sitemap_url:
        lines.append(f"Sitemap: {sitemap_url}")
    elif url:
        from urllib.parse import urlparse
        parsed = urlparse(url)
        base = f"{parsed.scheme}://{parsed.netloc}"
        lines.append(f"Sitemap: {base}/sitemap.xml")

    lines.append("")

    # llms.txt hint
    if url:
        from urllib.parse import urlparse
        parsed = urlparse(url)
        base = f"{parsed.scheme}://{parsed.netloc}"
        lines.append("# AI Content Index (experimental)")
        lines.append(f"# {base}/llms.txt")

    return "\n".join(lines)
